services:
  app:
    image: gauravsheth01/orders-api:latest
    container_name: orders-api
    ports:
      - "8000:8000"
    volumes:
      - .:$HOME  # Mount the project directory to /app inside the container
      - ./prod.db:$HOME/prod.db  # Map prod.db directly to the container's /app directory
    environment:
      - DATABASE_URL=sqlite:///app/prod.db  # Point the app to prod.db inside /app
    depends_on:
      - db

  db:
    image: busybox
    container_name: sqlite_db
    volumes:
      - sqlite_data:/app  # Optionally persist data in case you need it

volumes:
  sqlite_data:
